// Blog actions

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const MODIFY_POST_START = 'MODIFY_POST_START';
export const MODIFY_POST_FAILED = 'MODIFY_POST_FAILED';
export const MODIFY_POST_SUCCESS = 'MODIFY_POST_SUCCESS';

export const MODAL_CLOSE_ON_ERROR = 'MODAL_CLOSE_ON_ERROR';

/*-----------------------------------------------------------------*/
// Auth actions

export const RESET_ERRORS = 'RESET_ERRORS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';
export const REQ_RESET = 'REQ_RESET';
export const REQ_RESET_SUCCESS = 'REQ_RESET_SUCCESS';
export const REQ_RESET_FAILED = 'REQ_RESET_FAILED';
export const CHANGE_SUCCESS = 'CHANGE_SUCCESS';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';
export const PASS_CHANGE_SUCCESS = 'PASS_CHANGE_SUCCESS';

/*-----------------------------------------------------------------*/
// Paintings actions

export const CLOSE_ADMIN_MODAL = 'CLOSE_ADMIN_MODAL';

export const FETCH_MEMBERS_START = 'FETCH_MEMBERS_START';
export const FETCH_MEMBERS_FAILED = 'FETCH_MEMBERS_FAILED';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_PAINTINGS_SUCCESS';

export const POST_MEMBERS_START = 'POST_MEMBERS_START';
export const POST_MEMBERS_FAILED = 'POST_MEMBERS_FAILED';
export const POST_MEMBERS_SUCCESS = 'POST_PAINTINGS_SUCCESS';

export const DELETE_MEMBERS_START = 'DELETE_MEMBERS_START';
export const DELETE_MEMBERS_FAILED = 'DELETE_MEMBERS_FAILED';
export const DELETE_MEMBERS_SUCCESS = 'DELETE_MEMBERS_SUCCESS';
